// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbQe7NS4iAGgrTdIUfIT44Mg5bPMRQ0bE',
    appId: '1:1028131250421:web:03d116a3624cb0452de5bc',
    messagingSenderId: '1028131250421',
    projectId: 'abramoapp1',
    authDomain: 'abramoapp1.firebaseapp.com',
    storageBucket: 'abramoapp1.appspot.com',
    measurementId: 'G-H8RT0F16LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD4WPol9Xegf0czxG4Abg2kwxaBBNzCcM',
    appId: '1:1028131250421:android:531eb4473b31b19e2de5bc',
    messagingSenderId: '1028131250421',
    projectId: 'abramoapp1',
    storageBucket: 'abramoapp1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESlXqbsdvkuLX3vYcdcgB0pkNB089QSY',
    appId: '1:1028131250421:ios:488c078de5424fa02de5bc',
    messagingSenderId: '1028131250421',
    projectId: 'abramoapp1',
    storageBucket: 'abramoapp1.appspot.com',
    iosClientId: '1028131250421-inl84aolf62sbl2vd5sv906mn00874u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESlXqbsdvkuLX3vYcdcgB0pkNB089QSY',
    appId: '1:1028131250421:ios:488c078de5424fa02de5bc',
    messagingSenderId: '1028131250421',
    projectId: 'abramoapp1',
    storageBucket: 'abramoapp1.appspot.com',
    iosClientId: '1028131250421-inl84aolf62sbl2vd5sv906mn00874u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );
}
